### ISSUE TITLE
Issue with Intercom plugin

### ISSUE THREAD

**Issue by ninguemph** [Hypex-Technologies/hypex_plugin_rdvdatapad#1]
[nic_datapad_upd18.2] addons/nic_datapad_upd18.2/lua/rd_datapad/plugins/intercom/core/cl_plugin.lua:41: attempt to index global 'ply' (a nil value)
  1. DoClick - addons/nic_datapad_upd18.2/lua/rd_datapad/plugins/intercom/core/cl_plugin.lua:41
   2. unknown - addons/pixelui/lua/pixelui/elements/cl_button.lua:97 (x2)

**Comment by atlasuprising** [comment]
Fixed in commit - https://github.com/Hypex-Technologies/hypex_plugin_rdvdatapad/commit/52d210b774aa43b8c6137ae1948d5d37281daeee
